server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider

  cloud:
    nacos:
      discovery:
        server-addr: 39.96.71.220:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"